
name: CI

on: 
  schedule:
    - cron: "54 18 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch upstream
      uses: 135e2/sync-upstream-repo@v0.1.5
      with:
      #Git upstream repo
        upstream_repo: https://git.savannah.gnu.org/git/guile.git
        upstream_branch: main
        local_branch: main
	
