name: FreeBSD VM

on:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build and Run
      uses: vmactions/freebsd-vm@v0
      with:
        prepare: >-
          pkg install -y
          texlive-base
          texinfo
          autoconf
          automake
          m4
          llvm
          libtool
          gettext
          gperf
          pkgconf
          lzip
          boehm-gc-threaded
          gettext-runtime
          gettext-tools
          gmake
          gmp
          indexinfo
          libffi
          libiconv
          libltdl
          libtextstyle
          libunistring
          pkgconf
        run: |
          export LANG=C.UTF-8 LD_LIBRARY_PATH=/usr/local/lib PKG_CONFIG_PATH=/usr/local/lib/pkgconfig PATH="/usr/local/bin:$PATH"
          mkdir `pwd`/app
          autoreconf -vif
          ./configure MAKE=gmake CFLAGS="-g -O2 -Wall" CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" --prefix=`pwd`/app --enable-mini-gmp --with-libunistring-prefix=/usr/local --with-bdw-gc=bdw-gc-threaded
          gmake V=1
          gmake check V=1
    - name: Archive Test Logs
      if: success() || failure ()
      uses: actions/upload-artifact@v3
      with:
        name: Test Logs
        path: ./*.log
   
    
