name: MinGW w/ Guile 3.0

on:
  push:
    branches:
      - wip-mingw-guile-3.0
  pull_request:
    branches: 
      - wip-mingw-guile-3.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - threads: --without-threads
            jit: --enable-jit=no
          - threads: --with-threads
            jit: --enable-jit=no
          - threads: --without-threads
            jit: --enable-jit=yes
          - threads: --with-threads
            jit: --enable-jit=yes
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: false
        install: >-
          base-devel
          git
          mingw-w64-i686-toolchain
          mingw-w64-i686-gc
          mingw-w64-i686-libtool
          mingw-w64-i686-libunistring
          mingw-w64-i686-gobject-introspection
    - name: env
      run: export LANG=C TERM=dumb VERBOSE=true TZ=America/Los_Angeles
    - name: bootstrap
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS="-g -O2 -Wall" ${{ matrix.jit }} ${{ matrix.threads }} --enable-verbose-tests
    - name: make
      run: make -j2
    - name: make check
      run: make check
