name: MinGW w/ Guile 3.0

on:
  push:
    branches: [ master wip-mingw-guile-3.0 ]
  pull_request:
    branches: [ master wip-mingw-guile-3.0 ]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: false
        install: >-
          base-devel
          git
          mingw-w64-i686-toolchain
          mingw-w64-i686-gc
          mingw-w64-i686-libtool
          mingw-w64-i686-libunistring
          mingw-w64-i686-gobject-introspection
    - name: make dist directory
      run: mkdir `pwd`/dist
    - name: bootstrap
      run: ./autogen.sh
    - name: configure
      run: cd guile; ./configure --without-threads --enable-jit=no --prefix=`pwd`/dist
    - name: make
      run: make
    - name: make install
      run: make install
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - name: make dist
      run: make dist
    - name: Uncompress tarballs
      run: gunzip *.tar.gz
    - name: Archive tarball
      uses: actions/upload-artifact@v2
      with:
        name: tarball
        path: guile*tar
    - name: make check
      run: make check
    - name: Archive test logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./*.log
