name: MSYS

on:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Set git to Linux line endings
      run: git config --global core.autocrlf input
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: >-
          autotools
          gcc
          flex
          gperf
          lzip xz
          pkgconf
          gettext-devel
          gmp-devel
          libffi-devel
          libgc-devel
          libiconv-devel
          libintl
          libreadline-devel
          libunistring-devel
          texinfo
    - name: Configure
      run: |
          export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
          mkdir `pwd`/app
          ./autogen.sh
          ./configure CFLAGS="-g -O2 -Wall" --prefix=`pwd`/app
      shell: msys2 -o igncr '{0}'
    - name: Make
      run: |
        make -j4 V=1
      shell: msys2 -o igncr '{0}'
    - name: Run Unit Tests
      run: |
        make check V=1
      shell: msys2 -o igncr '{0}'
    - name: Archive test logs
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: Test logs
        path: ./*.log
