name: Ubuntu Guile 3.0

on:
  push:
    branches:
      - wip-mingw-guile-3.0
  pull_request:
    branches:
      - wip-mingw-guile-3.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            threads: --without-threads
            jit: --enable-jit=no
          - os: ubuntu-20.04
            threads: --with-threads
            jit: --enable-jit=yes

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
    - name: install packages
      run: sudo apt-get install -y gnulib texlive lzip gzip xzip libunistring-dev libgmp-dev libgc-dev libltdl-dev libncurses-dev libreadline-dev
    - name: bootstrap
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS="-g -O2 -Wall" ${{ matrix.jit }} ${{ matrix.threads }}
    - name: make
      run: make -j2
    - name: make check
      run: make check
    - name: Archive test logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./*.log
