name: Ubuntu CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set environ
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
    - name: install packages
      run: sudo apt-get install -y texlive autoconf libtool gettext autopoint gperf pkg-config lzip libgc-dev libgmp-dev libltdl-dev libncurses5-dev libreadline6-dev libunistring-dev
    - name: bootstrap with autogen.sh
      run: ./autogen.sh

    - name: configure
      run: |
        mkdir app
        ./configure CFLAGS="-g -O2 -Wall" --prefix=`pwd`/app
    - name: Archive config log
      uses: actions/upload-artifact@v3
      with:
        name: config log
        path: |
          config.log
          config.h
    - name: make
      run: make V=1
    - name: make binary package
      run: make install
    - name: Archive binary package
      uses: actions/upload-artifact@v3
      with:
        name: binary package
        path: app

    - name: make check
      run: make check V=1
    - name: Archive test logs
      uses: actions/upload-artifact@v3
      with:
        name: test log
        path: check-guile.log
    - name: make distcheck
      run: |
        make distcheck
        gunzip *.tar.gz
    - name: archive source package
      uses: actions/upload-artifact@v3
      with:
        name: source archive
        path: guile*tar
