name: Ubuntu 20.04 and 22.04

on:
  # 13:20 PDT
  schedule:
    - cron: "20 20 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: env
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
    - name: install packages
      run: sudo apt-get install -y texlive autoconf libtool gettext autopoint gperf pkg-config lzip libgc-dev libgmp-dev libltdl-dev libncurses5-dev libreadline6-dev libunistring-dev
    - name: make dist directory
      run: mkdir `pwd`/dist
    - name: bootstrap with autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS="-g -O2 -Wall" --prefix=`pwd`/dist
    - name: make
      run: make
    - name: make check
      run: |
        make check
        if [ -f check-guile.log ]; then
          cat check-guile.log
        fi
      shell: bash {0}
    - name: make install
      run: make install
    - name: make dist
      run: make dist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Uncompress tarballs
      run: gunzip *.tar.gz
    - name: Archive tarball
      uses: actions/upload-artifact@v3
      with:
        name: tarball
        path: guile*tar
    - name: Archive test logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: check-guile.log
