name: Windows MinGW UCRT64

on:
  # 12:20 PDT
  # schedule:
  #   - cron: "20 19 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 -o igncr {0}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >-
            base-devel
            git
            gperf
            autotools
            lzip
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-gc
            mingw-w64-ucrt-x86_64-libtool
            mingw-w64-ucrt-x86_64-libunistring
      - name: Bootstrap Guile
        run: |
          export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
          mkdir `pwd`/dist
          ./autogen.sh
      - name: Configure
        run: ./configure CFLAGS="-g -O2 -Wall" --enable-jit=no --enable-mini-gmp --disable-lto --prefix=`pwd`/dist
      - name: Make
        run: make V=1
      - name: Make Binary Package
        run: make install V=1
      - name: Archive installed files
        uses: actions/upload-artifact@v3
        with:
          name: Binary archive
          path: dist
          
      - name: Run tests
        run: |
          # git config --global --add safe.directory /cygdrive/d/a/guile/guile
          make check V=1
      - name: Archive test logs
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test logs
          path: check-guile.log

      - name: Make source tarball
        run: |
          make dist-gzip
          gunzip *.tar.gz
      - name: Archive source tarball
        uses: actions/upload-artifact@v3
        with:
          name: Source archive
          path: guile*tar
